### ISSUE TITLE
Swap XY on WaveShare32b

### ISSUE THREAD

**Issue by MaxChernotsky** [swkim01/waveshare-dtoverlays#1]
Hey man, 

Thanks for this overlay, finally got the touch working on my RPi2!
Anyway, is there some way in which you could change the x and y axis. When i move right, it goes up, and vice versa.

**Comment by swkim01** [comment]
Then, you have to calibrate touch position as to [FBTFT wiki](https://github.com/notro/fbtft/wiki/FBTFT-on-Raspian).
Then, you can change the axes.

**Comment by swkim01** [comment]
Check out "swapxy" option.
