### ISSUE TITLE
4.4 kernel seems to break LCD display

### ISSUE THREAD

**Issue by alexruffell** [swkim01/waveshare-dtoverlays#10]
I have been using your overlays for quite a while. Thanks for your contribution!

I recently updated both of my RPI2 & RPI3 to the latest firmware based on 4.4 kernel and the screens have turned white. If I downgrade it all starts working again. I was told your dtb files may need to be updated to support the new kernel in the following issue:

https://github.com/raspberrypi/firmware/issues/590

Thanks again!

**Comment by swkim01** [comment]
Thank you for the information. You have to rename the dtb file. Please see the updated Readme.md again.

**Comment by alexruffell** [comment]
Yes, renaming the file fixed the issue. Thanks!

**Comment by HorstBaerbel** [comment]
I have the same problem here. Both the original dtb by you (before my pull request) and my new one do not work on RPi 4.4.9+. I copied to .dtbo and removed the .dtb, but no change. I also tried moving the dtoverlay= line up and down in /boot/config.txt
sudo vcdbg log msg tells me that the overlay simply "failed to load".

I also posted [here](https://github.com/notro/fbtft/issues/388) in fbtft issues.

**Comment by swkim01** [comment]
My one works normally by your file on RPi 2/3 linux 4.4.9-v7+. I renamed waveshare35a-overlay.dtb to /boot/overlays/waveshare35a.dtbo.

**Comment by HorstBaerbel** [comment]
I have a RPi zero. Could that be a problem? I only have a white screen since upgrading to 4.4.9+ :(

**Comment by HorstBaerbel** [comment]
Wow. That was stupid. I renamed waveshare35a-overlay.dtbo to waveshare35a.dtbo and voila, it works. I was totally blind to that name thing. Sorry...
