### ISSUE TITLE
can't get it to work on raspberry 3 3.2 LCD

### ISSUE THREAD

**Issue by aoyawale** [swkim01/waveshare-dtoverlays#15]
hello,

I just tried this on my raspberry pie 3 and it just changes the screen to the terminal with some output but, never finishes loading.

kernel 4.4.38-v7+ jessie 
http://www.waveshare.com/wiki/3.2inch_RPi_LCD_(B)

**Comment by ravenousld3341** [comment]
My screen is just white. I can't quite figure it out. I'm going to re-image my SD card and start over again tonight.

I'm trying to get it to work on a raspberry pi 2, but it sounds like your luck has been better than mine. All i get is white screen.

Could you share the process to get you this far, perhaps I can get your GUI up.

(same screen fyi)

**Comment by alexruffell** [comment]
Around the beginning of March if I recall correctly, there was a firmware update that caused my LCD to go white. It is till white but today I found some error messages that may reveal what is going on:

![image](https://cloud.githubusercontent.com/assets/4006944/26735440/9c8b2122-4787-11e7-8b9b-2262b827db4e.png)

Can anyone suggest what to do? Is this an overlay issue or an RPI firmware issue?
