### ISSUE TITLE
waveshare-dtoverlays & kernel 4.9.xx - not working

### ISSUE THREAD

**Issue by alexruffell** [swkim01/waveshare-dtoverlays#17]
As soon as I updated my firmware to 4.9.13 the LCD stopped working. I do not know enough to determine whether it is an overlay issue but last time it was resolved by an update. Could you kindly verify it?

**Comment by swkim01** [comment]
I just tested waveshare35a overlay on 4.9.13 kernel. No problem. It works normally.

**Comment by alexruffell** [comment]
This morning I did an apt-get dist-upgrade and it fixed the issue. I had run one yesterday as well but the screen was white. I'd say whatever caused the issue was fixed yesterday. Thank you for checking!
