### ISSUE TITLE
No valid spi-max-frequency

### ISSUE THREAD

**Issue by mamoit** [swkim01/waveshare-dtoverlays#2]
I'm getting the following error:

```
spi_master spi0: /soc/spi@7e204000/waveshare35a-ts@1 has no valid 'spi-max-frequency' property (-22)
spi_master spi0: Failed to create SPI device for /soc/spi@7e204000/waveshare35a-ts@1
```

running 4.1.6 on rpi 2

The LCD switches from white to black.
Any idea on the cause?

**Comment by mamoit** [comment]
And my LCD is a `32b`, and is configured as such in the `config.txt` so I'm wondering why the `35a` error.

**Comment by swkim01** [comment]
I fixed the bug. Thank you for the comment.

**Comment by mamoit** [comment]
thank you :grinning:

**Comment by ftp2010** [comment]
> I fixed the bug. Thank you for the comment.

how do you fix it ? I get the same error on mt7628an openwrt.
Can you give some advises? thank you !
my dts :
spi {
                compatible = "spi-gpio";
                #address-cells = <1>;
                #size-cells = <0>;
                //ranges;

                sck-gpios = <&gpio 3 0>;
                miso-gpios = <&gpio 1 0>;
                mosi-gpios = <&gpio 0 0>;
                cs-gpios = <&gpio 6 0>;
                num-chipselects = <1>;

                lora@0 {
                        compatible = "semtech,sx1301";
                        reg = <0>;                    
                        spi-max-freqency = <1000000>;

                };
        };
