### ISSUE TITLE
waveshare35c.dtbo broken with latest Raspberry Pi firmware

### ISSUE THREAD

**Issue by dther** [swkim01/waveshare-dtoverlays#31]
Hey all. In the latest release of Raspberry Pi OS, a firmware change has broken most TFT screen device tree overlays.

I don't have nearly enough knowledge on how to operate dtc appropriately, but a workaround which worked for me is running:

     # rpi-update e1050e94821a70b2e4c72b318d6c6c968552e9a2

This should downgrade the Pi's firmware to allow the current .dtbo to work.

Looking at the code, it looks like this problem has been solved for waveshare35a screens, so I might take a crack at a patch when I have time.

For anyone who wants more info, I found the workaround here: https://github.com/goodtft/LCD-show/issues/223

**Comment by Zaryob** [comment]
Could you try [my fork](https://github.com/Zaryob/waveshare-overlays) and test it? I just recompile it and open PR #33 . It is working in my raspberry pi 4. 

And sorry for that late update. 🧷

**Comment by dther** [comment]
Hey there! I've tested it with the earlier compilation, and I've found that it works. I'll try and test the open PR when I have the time, my Pi 3B+'s SD card slot is broken and I haven't had the time to get a boot USB.

**Comment by dther** [comment]
Hello again! Sorry about the lack of update, I had to temporary shelve my Pi project due to real life circumstances. Your PR definitely works with the 3B+ with the latest RPi OS image. Thanks for your work!
