### ISSUE TITLE
option swapxy not recognized

### ISSUE THREAD

**Issue by Henry-Jones** [swkim01/waveshare-dtoverlays#6]
I can submit the option rotate=x in the config.txt file, and it also get recognized during bootup and is also visible in dmesg output.

All other options are also visible there (dmesg output), like regwidth, buswidth, debug, whether I set them or not.

But I've no luck in switching the x and y axis as per readme.md and waveshare35b.dts.
I tried "swapxy", "swap_xy", "swap-xy" but none seems to work.

If I leave it be and try to calibrate the touch regardless of the axis mismatch with xinput-calibrator, it does not work.

**Comment by swkim01** [comment]
Thank you. I fixed the bug. Now you can use the option as "swapxy=0" or "swapxy=1".

**Comment by Henry-Jones** [comment]
Impressive. Now it works as expected. Meanwhile I had hacked it in form via xinput "Transform Coordinates" but combined with a dualscreen setup this proved to be a challenge ;)

At least for me (4 Inch waveshare display), the combination of rotate=270 and swapxy=1 matches the display and touch orientation without any further configuration. Maybe this can become the standard for the waveshare displays.

But for this issue, succesfully closed.
