### ISSUE TITLE
easy question: how rotate display AND touchscreen?

### ISSUE THREAD

**Issue by jpwynn** [swkim01/waveshare-dtoverlays#7]
If you rotate the display you of course must also rotate the touchscreen.

What is the correct syntax in /boot/config.txt to  rotate both display and touchscreen using the waveshare32b overlay ?

```
dtoverlay=waveshare32b:rotate=270:swapxy=1 # DOES NOT WORK
dtoverlay=waveshare32b:rotate=270 swapxy=1 # DOES NOT WORK
dtoverlay=waveshare32b:rotate=270 swap-xy=1 # DOES NOT WORK
dtoverlay=waveshare32b:rotate=270: wap_xy=1 # DOES NOT WORK
```

**Comment by swkim01** [comment]
How about this?
`dtoverlay=waveshare32b:rotate=270,swapxy=1`

**Comment by jpwynn** [comment]
Yes, perfect, thank you! (All the other LCD display dtoverlays I've used use spaces as the delimiter, I did not think to try comma)

**Comment by Anteino** [comment]
I have an ads7846  waveshare 7 1024x600 and I tried every possible combination of dtoverlay, xinput_calibrator, display_rotate, lcd_rotate (doesn't do anything at all) and ts_calibrate (does not respond to touch at all). Is there a special technique to the ads7846? By the way when I use xinput_calibrator, the snippet I get asked to write to /etc/X11/xorg.conf.d/99-calibration.conf says my input device is called "RPI_TOUCH By ZH851". I really don't know how to proceed anymore. Could you guide me?

**Comment by swkim01** [comment]
You must confirm your device whether its touchscreen device is connected to spi gpio port or usb.
If spi gpio port, that device is a kind of ads7846, thus you can install ads7846 overlay by following commands.
`$sudo nano /boot/config.txt`
` dtparam=spi=on`
` dtoverlay=ads7846,penirq=25,speed=10000,penirq_pull=2,xohms=150`

But if it is conneced to usb port, then you don't need any overlay driver. Maybe when it is connected, the usb driver(eGalax touchscreen driver?) would be installed automatically. Then you can use additional input driving program as follows.
[https://github.com/derekhe/waveshare-7inch-touchscreen-driver](https://github.com/derekhe/waveshare-7inch-touchscreen-driver)
