### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Sandbird** [swkim01/waveshare-dtoverlays#8]
Hi, I've used this method on a Pi1, using the latest Raspbian from Noobs. I've added 
`fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo`
on my cmdline.txt and i could see the console boot up messages just fine, but while the pi goes to startx, i get a black screen, no arrow no nothing.

I am using this on my config.txt:

```
dtoverlay=waveshare32b:rotate=90,swapxy
hdmi_cvt=320 240 60 1 0 0 0
hdmi_group=2
hdmi_mode=87
```

which is fine for my Waveshare 3'2 V4 display.
Do you know whats going on ?
Thanks

**Comment by swkim01** [comment]
Did you change to /dev/fb1 in /usr/share/X11/xorg.conf.d/99-fbturbo.conf ?

**Comment by Sandbird** [comment]
Yup that was it :) Thanks man.
